name: 🐛 Bug Report
description: Report an issue.
labels: [bug]
title: "[BUG] "
body:
  - type: checkboxes
    attributes:
      label: Please confirm the following.
      options:
        - label: I checked the [existing issues](https://github.com/Cashtastrophe/Minecraft-Adventures-Plus/issues) for duplicate issues
          required: true
        - label: I have tried resolving the issue.
          required: true
        - label: I have a instaltion with no modifactions made.
          required: true
  - type: input
    id: version
    attributes:
      label: What version of the Adventures+ are you using?
      description: Find this in the main menu (bottom left)
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating systems are you using?
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Include screenshots if applicable.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce (if known)
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior (optional)
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context (optional)
      description: Add any other context about the problem here.
    validations:
      required: false
